
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [
  commit-msg,
  pre-push,
]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      # - id: trailing-whitespace
      - id: end-of-file-fixer
        stages: [commit-msg]
      # - id: check-yaml
      # - id: check-added-large-files
  - repo: local
    hooks:
      - id: git-secrets
        name: Git Secrets
        description: git-secrets scans commits, commit messages, and --no-ff merges to prevent adding secrets into your git repositories.
        entry: 'scripts/git-secrets/pre-commit.sh'
        language: script
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        stages: [commit-msg]
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
        stages: [commit-msg]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.9.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
