"""Parquet readers for DuckDB"""

from collections.abc import Iterator
from typing import Any, Optional

import duckdb as ddb
from duckdb import BinderException, DuckDBPyConnection, DuckDBPyRelation
from pydantic import BaseModel

from dve.core_engine.backends.base.reader import read_function
from dve.core_engine.backends.exceptions import EmptyFileError, UnableToParseParquetError
from dve.core_engine.backends.implementations.duckdb.duckdb_helpers import (
    duckdb_record_index,
    duckdb_write_parquet,
    get_duckdb_type_from_annotation,
)
from dve.core_engine.backends.implementations.duckdb.types import SQLType
from dve.core_engine.backends.readers.parquet import BaseParquetReader
from dve.core_engine.backends.readers.utilities import get_parquet_metadata_row_count
from dve.core_engine.type_hints import URI, EntityName


@duckdb_record_index
@duckdb_write_parquet
class DuckDBParquetReader(BaseParquetReader):
    """A DuckDB parquet reader."""

    def __init__(
        self,
        *,
        hive_partitioning: bool = False,
        binary_as_string: bool = False,
        connection: Optional[DuckDBPyConnection] = None,
        field_check_error_code: str = "ParquetFieldMismatch",
        field_check_error_message: str = "The submitted fields are invalid",
        **_,
    ):
        self.binary_as_string = binary_as_string
        """
        Parquet files generated by legacy writers do not correctly
        set the UTF8 flag for strings, causing string columns to be
        loaded as BLOB instead. Set this to true to load binary columns
        as strings.
        """
        self.connection = connection if connection else ddb.connect(":memory:")
        """DuckDB connection. Creates an in memory ddb connection if not supplied."""
        super().__init__(
            hive_partioning=hive_partitioning,
            field_check_error_code=field_check_error_code,
            field_check_error_message=field_check_error_message,
        )

    def read_to_py_iterator(
        self,
        resource: URI,
        entity_name: EntityName,
        schema: type[BaseModel],
        all_model_fields: Optional[set[str]] = None,  # pylint: disable=W0613
    ) -> Iterator[dict[str, Any]]:
        """Creates an iterable object of rows as dictionaries"""
        # TODO - these are actually loading entire relations into memory (csv & json imps as well)
        # TODO - no out of the box offering for iterating records of a ddb relation
        return self.read_to_relation(resource, entity_name, schema).pl().iter_rows(named=True)

    @read_function(DuckDBPyRelation)
    def read_to_relation(
        self,
        resource: URI,
        entity_name: EntityName,
        schema: type[BaseModel],
        all_model_fields: Optional[set[str]] = None,  # pylint: disable=W0613
    ):
        """Read a Parquet file to a Polars DataFrame"""
        if get_parquet_metadata_row_count(resource) == 0:
            raise EmptyFileError(f"File at {resource} is empty.")

        reader_options: dict[str, Any] = {
            "hive_partitioning": self.hive_partioning,
            "binary_as_string": self.binary_as_string,
        }

        ddb_schema: dict[str, SQLType] = {
            name: str(get_duckdb_type_from_annotation(fld.annotation))  # type: ignore
            for name, fld in schema.model_fields.items()
        }

        try:
            relation = self.add_record_index(
                self.connection.read_parquet(resource, **reader_options).select(*ddb_schema.keys())
            )
        except BinderException as exc:
            raise UnableToParseParquetError(
                entity_name, self.field_check_error_message, self.field_check_error_code
            ) from exc

        return relation
